=pod

=head1 NAME

Plack::Middleware::Throttle::Lite - Requests throttling for Plack

=head1 VERSION

version 0.101

=head1 DESCRIPTION

=head1 DESCRIPTION

=head1 SYNOPSYS

=head1 OPTIONS

=head1 METHODS

=head2 prepare_app

=head2 call

=head1 BUGS

=head1 SEE ALSO

L<Plack>

L<Plack::Middleware>

=head1 AUTHOR

Anton Gerasimov <chim@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2013 by Anton Gerasimov.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

